# Generated by Django 5.2.6 on 2025-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("base", "0002_alter_provider_credentials"),
        ("base", "0003_providerlink_extra_data_and_more"),
        ("base", "0004_add_provider_config_fields"),
        ("base", "0005_add_provider_opt_out_fields"),
        ("base", "0004_providerlink_linked_at"),
        ("base", "0006_merge_20250924_1242"),
    ]

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="credentials",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providerlink",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="providerlink",
            unique_together={("provider", "user")},
        ),
        migrations.AlterField(
            model_name="provider",
            name="provider_type",
            field=models.CharField(
                choices=[("beurer", "Beurer"), ("fitbit", "Fitbit"), ("omron", "Omron"), ("withings", "Withings")],
                default="withings",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="excluded_data_types",
            field=models.JSONField(default=list, help_text="Data types to exclude from sync (opt-out)"),
        ),
        migrations.AddField(
            model_name="provider",
            name="webhook_enabled",
            field=models.BooleanField(default=True, help_text="Enable webhook subscriptions for this provider"),
        ),
        migrations.AddField(
            model_name="provider",
            name="default_data_types",
            field=models.JSONField(
                default=list, help_text="Default data types for health sync (empty = use provider config defaults)"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="supports_webhooks",
            field=models.BooleanField(default=True, help_text="Provider supports webhook subscriptions"),
        ),
        migrations.AddField(
            model_name="providerlink",
            name="linked_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Timestamp when the provider link was created"),
        ),
    ]
