# Generated by Django 5.2b1 on 2025-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="credentials",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
