# Generated by Django 5.2.6 on 2025-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_provider_credentials_squashed_0006_merge_20250924_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="error_deeplink_url",
            field=models.URLField(
                blank=True,
                help_text="Optional deeplink URL for mobile app error redirect (e.g., myapp://oauth/error/withings/)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="success_deeplink_url",
            field=models.URLField(
                blank=True,
                help_text="Optional deeplink URL for mobile app success redirect (e.g., myapp://oauth/success/withings/)",
                max_length=500,
                null=True,
            ),
        ),
    ]
